config/routes.rb
ChequeItOut::Application.routes.draw do
  get "home/index"
  root :to => "home#index"
  resources :cheques
end

app/models/cheque.rb
class Cheque < ActiveRecord::Base
  attr_accessible :amount, :drawer, :payee

  validates :amount, :drawer, :payee, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cheques_controller.rb
class ChequesController < ApplicationController

  # Cheques shown are based on if a selected name is a drawer or payer (or both).
  def index
    if params[:drawer]
      @cheques = Cheque.where(:drawer => params[:drawer])

    elsif params[:payee]
      @cheques = Cheque.where(:payee => params[:payee])

    elsif params[:drawer_payee]
      @cheques_drawer = Cheque.where(:drawer => params[:drawer_payee])
      @cheques_payee = Cheque.where(:payee => params[:drawer_payee])
      @cheques = @cheques_drawer + @cheques_payee

    else
      @cheques = Cheque.all
      
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cheques }
    end
  end

  # GET /cheques/1
  # GET /cheques/1.json
  def show
    @cheque = Cheque.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cheque }
    end
  end

  # GET /cheques/new
  # GET /cheques/new.json
  def new
    @cheque = Cheque.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cheque }
    end
  end

  # GET /cheques/1/edit
  def edit
    @cheque = Cheque.find(params[:id])
  end

  # POST /cheques
  # POST /cheques.json
  def create
    @cheque = Cheque.new(params[:cheque])

    respond_to do |format|
      if @cheque.save
        format.html { redirect_to @cheque, notice: 'Cheque was successfully created.' }
        format.json { render json: @cheque, status: :created, location: @cheque }
      else
        format.html { render action: "new" }
        format.json { render json: @cheque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cheques/1
  # PUT /cheques/1.json
  def update
    @cheque = Cheque.find(params[:id])

    respond_to do |format|
      if @cheque.update_attributes(params[:cheque])
        format.html { redirect_to @cheque, notice: 'Cheque was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cheque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cheques/1
  # DELETE /cheques/1.json
  def destroy
    @cheque = Cheque.find(params[:id])
    @cheque.destroy

    respond_to do |format|
      format.html { redirect_to cheques_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheques_helper.rb
module ChequesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cheques/_form.html.erb
<%= form_for(@cheque) do |f| %>
  <% if @cheque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cheque.errors.count, "error") %> prohibited this cheque from being saved:</h2>

      <ul>
      <% @cheque.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :drawer %><br />
    <%= f.text_field :drawer, :placeholder => 'Mr. Smith' %>
  </div>
  <div class="field">
    <%= f.label :payee %><br />
    <%= f.text_field :payee, :placeholder => 'Mrs. Smith' %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <strong style="font-size:25px">$</strong>
    <%= f.text_field :amount, :placeholder => '100.00' %>
  </div>

    <%= f.submit "Save cheque", class: "btn btn-primary" %>

<% end %>

app/views/cheques/edit.html.erb
<h1>Editing cheque</h1>

<%= render 'form' %>

<%= link_to 'Show', @cheque, :class => 'btn btn-info' %> |
<%= link_to 'Back', cheques_path, :class => 'btn btn-warning' %>

app/views/cheques/index.html.erb
<!--The following code determines what headline and buttons to show based on the parameters in the address bar-->

<% if !params[:drawer] && !params[:payee] && !params[:drawer_payee] %>
  <h3>All Cheques</h3>

<% elsif params[:drawer] %>
  <h3>Cheques made by <%= params[:drawer] %></h3>

  <%= link_to "Cheques made out to " + params[:drawer], cheques_path(:payee => params[:drawer]), :class => 'btn btn-mini btn-inverse' %>

  <%= link_to "Cheques made out to and by " + params[:drawer], cheques_path(:drawer_payee => params[:drawer]), :class => 'btn btn-mini btn-inverse' %>

<% elsif params[:payee] %>
  <h3>Cheques made out to <%= params[:payee] %></h3>

  <%= link_to "Cheques made by " + params[:payee], cheques_path(:drawer => params[:payee]), :class => 'btn btn-mini btn-inverse' %>

  <%= link_to "Cheques made out to and by " + params[:payee], cheques_path(:drawer_payee => params[:payee]), :class => 'btn btn-mini btn-inverse' %>

<% elsif params[:drawer_payee] %>
  <h3>Cheques made out to and by <%= params[:drawer_payee] %></h3>
  
  <%= link_to "Cheques made out to " + params[:drawer_payee], cheques_path(:payee => params[:drawer_payee]), :class => 'btn btn-mini btn-inverse' %>

  <%= link_to "Cheques made by " + params[:drawer_payee], cheques_path(:drawer => params[:drawer_payee]), :class => 'btn btn-mini btn-inverse' %>

<% end %>

<br>
<br>

<!-- Table of cheque values. -->

<table class="table">
  <tr>
    <th>Drawer</th>
    <th>Payee</th>
    <th>Date</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cheques.each do |cheque| %>
  <tr>
    <!-- clicking on a name adds their name to the address parameters -->
    <td>
      <%= link_to cheque.drawer, cheques_path(:drawer => cheque.drawer), :class => 'name' %>
    </td>
    <td>
      <%= link_to cheque.payee, cheques_path(:payee => cheque.payee), :class => 'name' %>
    </td>
    <td>
      <%= cheque.created_at.strftime("%m/%d/%Y") %>
    </td>
    <td>
      <!-- integer amount shown as proper currency value-->
      <price><%= number_to_currency(cheque.amount) %></price>
    </td>
    <td>
      <!-- if a name has been selected then give the option to show all cheques again -->
      <%= link_to 'Show All', cheques_path, :class => 'btn btn-primary', :style => 'float:right' if params[:drawer] || params[:payee] || params[:drawer_payee] %>
    </td>
    <td>
      <%= link_to 'Show', cheque, :class => 'btn btn-info', :style => 'float:right' %>
    </td>
    <td>
      <%= link_to 'Edit', edit_cheque_path(cheque), :class => 'btn btn-success', :style => 'float:right' %>
    </td>
    <td>
      <%= link_to 'Destroy', cheque, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cheque', new_cheque_path, :class => 'btn btn-primary' %>

app/views/cheques/new.html.erb
<h1>New cheque</h1>

<%= render 'form' %>

<%= link_to 'Back', cheques_path, :class => 'btn btn-warning' %>

app/views/cheques/show.html.erb
<!-- Show a blank cheque image with dynamic text overlaying it -->

<div align="center">

	<%= image_tag "blank_cheque.jpg", :style => "min-width:1000px; position:relative" %>

	<div class="container" style = "position:relative">

		<h2 style="position:absolute; bottom:80px; left:620px;"><%= @cheque.drawer %></h2>

		<h2 style="position:absolute; bottom:230px; left:300px"><%= @cheque.payee %></h2>

		<h3 style="position:absolute; bottom:295px; left:850px">
			<%= @cheque.created_at.strftime("%m/%d/%Y") %>
		</h3>

		<% @amount_as_words = number_with_precision @cheque.amount, :precision => 2 %>
		<% @word_count = @amount_as_words.length %>
		<% if @word_count > 7 %>
			<h3 style="position:absolute; bottom:225px; left:880px">
				<%= number_with_precision @cheque.amount, :precision => 2 %>
			</h3>
		<% else %>
			<h2 style="position:absolute; bottom:225px; left:880px">
				<%= number_with_precision @cheque.amount, :precision => 2 %>
			</h2>
		<% end %>

		<% @amount_as_words = number_to_currency_in_words(@cheque.amount, connector: ' and ') %>
		<% @word_count = @amount_as_words.length %>
		<% if @word_count > 35 %>
			<h4 style="position:absolute; bottom:180px; left:130px">
				<%= number_to_currency_in_words(@cheque.amount, connector: ' and ') %>
			</h4>
		<% elsif @word_count > 20 && @word_count < 35 %>
			<h3 style="position:absolute; bottom:180px; left:250px">
				<%= number_to_currency_in_words(@cheque.amount, connector: ' and ') %>
			</h3>
		<% else %>
			<h2 style="position:absolute; bottom:180px; left:250px">
				<%= number_to_currency_in_words(@cheque.amount, connector: ' and ') %>
			</h2>
		<% end %>

	</div>
</div>

<hr>

<!-- Text-only version of the cheque in case the cheque image and text doesn't display properly-->

<div class="row-fluid">
	<div class="span8">
		<h5>
			<%= @cheque.drawer + '\'s cheque to ' + @cheque.payee %>
			<%= 'to the amount of ' + number_to_currency_in_words(@cheque.amount, connector: ' and ') %>
			(or <price><%= number_to_currency(@cheque.amount) %></price>)
			<%= 'dated at ' + @cheque.created_at.strftime("%m/%d/%Y") %>
		</h5>
	</div>
	<div class="span4">
		<h3 align="center"><%= link_to 'Edit', edit_cheque_path(@cheque), :class => 'btn btn-success' %> |
		<%= link_to 'Back', cheques_path, :class => 'btn btn-warning' %></h3>
	</div>
</div>

app/views/home/index.html.erb
<h3>Welcome to Cheque-it-Out</h3>

<h4>The brand new app for chequing out cheques! </h4>
<br>

<h5>See your entire cheque list <%= link_to "here", cheques_path, :class => 'name', :style => 'color:#597543' %> or create a <%= link_to "new cheque", new_cheque_path, :class => 'name', :style => 'color:#597543' %></h5>
<br>

<p>This app is developed in rails and bootstrap, hosted on heroku and uses bcarrere's <a href="https://github.com/bcarrere/currency-in-words", target = "_blank", style ="color:#597543">currency-in-words gem</a> to get the cheque amounts properly converted into words.</p>

<p>To use the site you can use the navbar to go to the cheque list page where you can then view all your cheques, edit/delete/create cheques and view only cheques by sender or recipient (or both).</p>

<p>A cheque is created with just a name for the drawer (sender) and a name for the payee (recipient) as well as the monetary amount. For the date I was considering having a datetime field where the user can choose their own date with it set to today's date by default but for simplicity I decided that the date of the cheque would automatically be the date the cheque form is submitted. </p>

<p>Again to simplify I decided to use a gem for converting a number to a currency string output. I considered trying to do this conversion myself by perhaps converting the decimal amount to a string and then create a word based on each element character e.g. '1' = 'one'. Then by counting the length of the string I can determine by position in the string if this '1' is something like one thousand, one hundred or just.. one. But to avoid a whole lot of if and case statements I went the easy way out.</p>

<p>The site isn't fully responsive and I'm not all that good with CSS layouts so the text on the cheque show page may be a bit off but if your screen size is large enough it should hopefully work. There is a text-only version of the cheque at the bottom of the page just in case it doesn't.</p>

<p>My project can be found up on <a href="https://github.com/pjsim/Cheque-it-out.git", target="_blank", style ="color:#597543">GitHub</a>. Any feedback or bug reports would be much appreciated.</p>

app/views/layouts/_navigation.html.erb
<div class="navbar">
    <div class="navbar-inner", style ="background-color: #E5F5E1; background-image: none; padding-left:50px; padding-right:50px;">

        <%= link_to "Cheque-it-Out", root_path, :class => 'brand', :style => "float:left; font-family: 'Sail', cursive; font-size:40px; color: #1C451C" %>

        <%= image_tag "chequeLogo.png", :style => "width:50px; padding-top:4px; float:left" %>
        
        <ul class="nav">
            <li><%= link_to "Cheque List", cheques_path %></li>
        </ul>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChequeItOut</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Sail' rel='stylesheet' type='text/css'>
</head>
<body style="background-color: #CEE6C8; color: #020D01;">

	<%= render 'layouts/navigation' %>

	<div class="well" style="padding-left:40px; padding-right:40px; padding-bottom:40px; margin-left:30px; margin-right:30px;">
		<%= yield %>
	</div>
	
</body>
</html>